## OAuth authentication using Microsoft Graph API
## https://developer.microsoft.com/en-us/graph/graph-explorer/preview
$AccessToken = ConvertTo-SecureString 'eyJ0eXAiOiJKV1QiLCJub25jZSI6IjY4ZWlrRGdtMTZqNzRBYkVramxVTTVmb0x6bW4xeDNMa1lsRlVmdm5tLTgiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC84NmUyNjU2ZS0yMTE1LTQxNWMtYjcwZi05MmNjZjE4MzMzZTMvIiwiaWF0IjoxNjY4NDAzNDc1LCJuYmYiOjE2Njg0MDM0NzUsImV4cCI6MTY2ODQwNzU0NiwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhUQUFBQURMYzl5Z2FFSkM5cjRDaWFmV2dySDlnRy9CU2E5UnQrS2l0UE1RcmdxYmxEUTVNNUhUd3cyWTdQSVBiemcyNkNzMHFTYUUrZWVENG4yVEhOKzdXWkhGMjQ4Qk8yMm5EMkR1Tk9kM2hqRndJPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiR3JhcGggRXhwbG9yZXIiLCJhcHBpZCI6ImRlOGJjOGI1LWQ5ZjktNDhiMS1hOGFkLWI3NDhkYTcyNTA2NCIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiT2dvbWEiLCJnaXZlbl9uYW1lIjoiUmljaGFyZCIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjE5Ny4yMTAuMjI2LjgzIiwibmFtZSI6IlJpY2hhcmQgT2dvbWEiLCJvaWQiOiI1MTAxMjFjOC1jY2E3LTQ5NTMtODc0ZC03NGMzMTI0YzE2YzciLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwMzIwMDIxNDdCQTBBOCIsInJoIjoiMC5BWDBBYm1YaWhoVWhYRUczRDVMTThZTXo0d01BQUFBQUFBQUF3QUFBQUFBQUFBQ2NBUEEuIiwic2NwIjoib3BlbmlkIHByb2ZpbGUgVXNlci5SZWFkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiZXZESGRMeGR5YWdHWkp1T242MTJMdURlcjhnTE0yWFI3ZWlwVERGZHROVSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6Ijg2ZTI2NTZlLTIxMTUtNDE1Yy1iNzBmLTkyY2NmMTgzMzNlMyIsInVuaXF1ZV9uYW1lIjoicmljaGFyZEA3eWtqMTAub25taWNyb3NvZnQuY29tIiwidXBuIjoicmljaGFyZEA3eWtqMTAub25taWNyb3NvZnQuY29tIiwidXRpIjoiMzNnZWIyUHZyRVdBREZaVjZPc01BQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJDRUtPaXFpZW9zTmo0RC1nQ2twSTV4YXVId3p4YmdCWjcyREN1RUNkb0o4In0sInhtc190Y2R0IjoxNjU4NzIzMTU0fQ.fBy69-DCaWrkoGUOeO26gx1TRTZ_QcWjZKLLJI86eda3sFOVMG9Qvgos4VEGgLZbmp8bQP_WdVjuROUorKXKJPgXBoYdDgKC82Lfj735fXUEoowbHoA54zvJzswdzS3kNLfnt3N3Bp6MFBXoyF8mkf8Xt1Psf8So8YC1xRVc_6HGumD6XqYY60C2DyerhLfshijnojNfoFiGS76F9iclJAFqWPzoKpw4xDM8OqDpxw8JvgI7oxI_hntutwfdyc9u-i0ret52vvNDaWjCrx2RiO2Oc6grCbtUh5XJGoR_ZfMAbQzz0doLDFaH8X22rEjYm_bN7ZqQ5yTf_sIgqzFL4w' -AsPlainText -Force

$Params = @{
    "URI" = 'https://graph.microsoft.com/v1.0/me'
    "Method" = 'GET'
    # "Headers" = @{
    #     "Content-Type" = 'application/json'
    #     "Authorization" = 'Bearer'
    # }
    "Authentication" = 'Bearer'
    "Token" = $AccessToken
    "ContentType" = 'application/json'
}

$Response = Invoke-RestMethod @Params
$Response | 
    Select-Object displayName, @{Name="Phone";Expression={$_.businessPhones[0]}}, mail | ConvertTo-Json